name: Production-Ready

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-production:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: docker build
              run: |
                  cp .env.example .env.local
                  docker build -t app .
